name: build-windows-arm64

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Git repository to clone'
        required: true
        default: 'https://bitbucket.org/chromiumembedded/java-cef.git'
      ref:
        description: 'Git commit id to checkout'
        required: true
        default: 'master'

jobs:
  build-windows-arm64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      -
        name: Build
        shell: cmd
        run: |
          compile_windows.bat arm64 Release ${{ github.event.inputs.repo }} ${{ github.event.inputs.ref }}
      -
        name: Export artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-arm64.tar.gz
          path: out/binary_distrib.tar.gz

